### ISSUE TITLE
[Chore] 배포하기 전 빠져있는 잡다한 일들을 합니다. 

### ISSUE THREAD

**Issue by no1msh** [no1msh/DMC2-renewal#22]
## 어떤 기능인가요?
배포하기 전 빠져있는 잡다한 일들을 합니다. 

## To Do

- [x] 광고 배너 추가
- [x] 각종 카피라이트 추가
- [x] 다크모드 제거
- [x] 상태바 색상 제거
- [x] 키보드에 적응하는 화면 구현 
- [x] 음식 추천 카드 디자인 변경
- [x] 지도 마커 클릭 이벤트로 나오는 bottom sheet 내용 변경
- [x] 화면 로테이션 세로 고정
- [x] 앱 아이콘 적용
- [x] 스플래시 화면 적용
- [x] 업데이트 중 다이얼로그 구현 
- [x] 학식 툴바 붙이기
- [x] 복불복 카드 애니메이션 고치기
- [x] 꿀팁추천 더보기 고치기

**Comment by KangminNa** [comment]
확인했습니다. 이렇게만 진행하면 될 거 같습니다. 추후에 앱 심사 이후 API 관련 기능들 다시 업데이트 하는걸로 진행할게요.
순위는 1. 꿀팁추천, 2. 광고 배너, 3. 학식 순으로 해결하면 될 거 같습니다.
