### ISSUE TITLE
[Bug] 음식점 카테고리 레이아웃 안맞음

### ISSUE THREAD

**Issue by 2384320** [no1msh/DMC2-renewal#28]
**발견한 버그에 대해서 설명해주세요.**
지도에서 확인할 수 있는 필터와 음식점 추천 전에 나오는 카테고리 선택창의 레이아웃이 잘려서 나옵니다.

**재현 방법**
1. Go to '음식 추천'
2. See error

1. Go to '학교 주변 탐방 지도'
2. Click to filter
3. See error

**버그 발생 환경**
버그가 발생한 환경을 제시해주세요.
 - Device: 갤럭시 노트 10+
 - OS: Android 12
 - Version: DMC 1.0.0

**Screens**
지도 필터
![Screenshot_20230922_164106_DMC2](https://github.com/no1msh/DMC2-renewal/assets/71584474/174ceeca-ca70-4fa6-b67d-2189c768efff)

음식 추천 선택창
![Screenshot_20230922_163916_DMC2](https://github.com/no1msh/DMC2-renewal/assets/71584474/a7cce441-ead6-4944-826c-add20e55332e)
hots**

**추가적인 질문**
X

**Comment by KangminNa** [comment]
이것도 이미 말씀해주셨네요 Z플립4도 똑같은 상황입니다!~
