### ISSUE TITLE
[Bug] 문의하기 이메일 검증

### ISSUE THREAD

**Issue by 2384320** [no1msh/DMC2-renewal#29]
**발견한 버그에 대해서 설명해주세요.**
문의하기에서 이메일 양식에 맞춰서 작성하지 않아도 문의 처리가 완료됐다는 알림이 떠요.
대신 이메일 양식에 맞지 않으면 db에는 저장이 안돼요.

**재현 방법**
재현할 방법을 단계별로 제시해주세요.
1. Go to '문의하기'
2. Write all forms
3. Click on '작성 완료'
4. View completion notification
5. Go to '문의하기' database
6. Confirm that it is not saved
7. See error

**버그 발생 환경**
버그가 발생한 환경을 제시해주세요.
 - Device: 갤럭시 노트 10+
 - OS:  Android 12
 - Version: DMC 1.0.0

**Screenshots**
https://clipchamp.com/watch/Z6WgkWQoClp

**추가적인 질문**
X

**Comment by KangminNa** [comment]
적을려고 왔는데 굳!
